version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "ci(deps)"
      prefix-development: "ci(deps)"
      include: "scope"
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "build(deps)"
      prefix-development: "build(deps)"
      include: "scope"
    versioning-strategy: lockfile-only
    allow:
      - dependency-type: "all"
