[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "etpproto"
version = "0.0.0" # Set at build time
description = "ETP protocol implementation"
authors = [
    "Lionel Untereiner <lionel.untereiner@geosiris.com>"
]
maintainers = [
    "Lionel Untereiner <lionel.untereiner@geosiris.com>", 
    "Valentin Gauthier <valentin.gauthier@geosiris.com>"
]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/bp/resqpy"
homepage = "www.geosiris.com"
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: Apache Software License"
]
keywords = ["ETP"]

[tool.poetry.dependencies]
python = "^3.9,<3.11"
fastavro = "1.5.3"
coverage = {extras = ["toml"], version = "^6.2"}
etptypes = "^1.0.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"
flake8 = "^4.0.0"
black = "^22.3.0"
pytest-cov = "^3.0.0"
pre-commit = "^2.11.1"
pylint = "^2.7.2"
pytest-asyncio = "^0.18.0"
mypy = "^0.961"
click = ">=8.1.3, <=8.1.3" # upper version than 8.0.2 fail with black
isort = "^5.10.1"

[tool.black]
line-length = 79
target-version = ["py39"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.pytest_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | htmlcov
)/
'''

[tool.pytest.ini_options]
addopts = ""
console_output_style = "count"
python_classes = "Test"
python_files = "test_*.py"
python_functions = "test*"
testpaths = ["tests"]
asyncio_mode = "auto"

[tool.coverage.run]
branch = true
source = ["etpproto"]

[tool.pylint.format]
max-line-length = "88"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "pep440"
format-jinja = """
    {%- if distance == 0 -%}
        {{ serialize_pep440(base, stage, revision) }}
    {%- elif revision is not none -%}
        {{ serialize_pep440(base, stage, revision + 1, dev=distance) }}
    {%- else -%}
        {{ serialize_pep440(bump_version(base), stage, revision, dev=distance) }}
    {%- endif -%}
"""
